language: node_js

sudo: false

cache: 
  apt: true
  directories: 
    - node_modules

node_js: stable

install:
  - npm install -g pnpm
  - pnpm install -D
  - cd ./test/smoke/template
  - pnpm install -D

scripts:
  - pnpm test